[package]
name = "own-ref"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extension-traits.version = "1.0.1"
macro_rules_attribute.version = "0.1.3"
scopeguard.version = "1.1.0"
