use super::*;

mod args;

pub fn macro_(
    args: TokenStream2,
    input: TokenStream2,
) -> Result<TokenStream2>
{
    let mut ret = quote!();
    let args::Args {
        pub_: extension_trait_pub,
        TraitName: ExtensionTraitName @ _,
        rename,
        ..
    } = parse2(args).map_err(|mut err| {
        err.combine(Error::new(
            Span::mixed_site(),
            r#"usage: `#[dyn_self(as <pub> <TraitName> [, rename = "<prefix>{}<suffix>"])]`"#,
        ));
        err
    })?;
    let extension_trait_method_renaming_logic = &rename.map_or_else(<_>::default, |r| r.pattern);
    let mut input: ItemTrait = parse2(input)?;
    let Trait @ _ = &input.ident;
    let (intro_generics, fwd_generics, where_clause) = &input.generics.split_for_impl();
    // assert that the trait is `dyn`-safe.
    ret.extend(quote_spanned!(Span::mixed_site()=>
        impl #intro_generics dyn #Trait #fwd_generics
        #where_clause
        {}
    ));
    let mut mut_self_methods = Vec::<TraitItemFn>::new();
    let mut mut_self_method_impls = Vec::<TraitItemFn>::new();
    for trait_item in &input.items {
        // ignore / keep as-is the non-fn `trait` items;
        let TraitItem::Fn(trait_fn) = trait_item
        else {
            // TODO: handling assoc types. This would require having a companion
            // macro accompanying the `impl` parts, since the assoc types would
            // have to be hoisted into their own grandparent trait, so that
            // the `DynTraitOwnRef` one would have access to them without having
            // to provide them.
            return Err(Error::new_spanned(
                trait_item,
                "non-`fn` associated items are not supported yet.",
            ));
        };
        // Deny default bodies (can be confusing w.r.t. the blanket impl of `OwnRef`).
        if let Some(block) = &trait_fn.default {
            return Err(Error::new(
                block.brace_token.span.open(),
                "\
                    trait items cannot have default bodies/impls yet, since this could be \
                    confusing w.r.t. the autogenerated blanket impl for `OwnRef<impl YourTrait>`\
                ",
            ));
        }
        // ignore / keep as-is the non-methods;
        let Some(receiver) = trait_fn.sig.receiver()
        else {
            continue;
        };
        // ignore / keep as-is the non-owned-self-methods;
        if is_owned_self_receiver(&receiver).not() {
            continue;
        }
        let self_ = &receiver.self_token;
        // By now we must be dealing with an owned `self` method.
        let method = trait_fn;
        let method_name = &method.sig.ident;
        let mut_self_method = {
            // To be the same as `method` but for three things.
            let mut mut_self_method = method.clone();
            // 1. Make sure it is an unsafe fn.
            mut_self_method.sig.unsafety = parse_quote!(
                unsafe
            );
            // 2. `&mut self` instead of `self` receiver.
            *mut_self_method.sig.inputs.first_mut().unwrap() =
                parse_quote_spanned!(receiver.span()=>
                    & /* TODO: unelided lifetime */ mut #self_
                )
            ;
            // 3. mangle the name to prevent users from unknowingly calling it.
            mut_self_method.sig.ident = format_ident!(
                "ඞdyn_{method_name}_ownref"
            );
            mut_self_method
        };
        let mut_self_method_impl = {
            let mut mut_self_method_impl = mut_self_method.clone();
            let mut each_fn_arg = Vec::<Ident>::new();
            // Make sure the args are forwardable (_e.g._, `ident` patterns).
            mut_self_method_impl
                .sig
                .inputs
                .iter_mut()
                .zip(0..)
                .skip(1)
                .for_each(|(fn_arg, i)| {
                    let FnArg::Typed(fn_arg) = fn_arg
                    else {
                        unreachable!();
                    };
                    let arg_ident = format_ident!("ඞ{i}", span=fn_arg.pat.span());
                    *fn_arg.pat = Pat::Verbatim(quote!(
                        #arg_ident
                    ));
                    each_fn_arg.push(arg_ident);
                })
            ;
            mut_self_method_impl.semi_token = None;
            mut_self_method_impl.default = Some(parse_quote!({
                let this: ඞSelf = unsafe {
                    // SAFETY: as per the caller precondition;
                    // this is morally equivalent to `ManuallyDrop::take()`.
                    <*const ඞSelf>::read(#self_)
                };
                <ඞSelf as #Trait #fwd_generics>::#method_name(
                    this #(, #each_fn_arg)*
                )
            }));
            mut_self_method_impl
        };
        mut_self_methods.push(mut_self_method);
        mut_self_method_impls.push(mut_self_method_impl);
    }
    let mut_self_trait = {
        let items = mem::take(&mut input.items);
        let mut mut_self_trait = input.clone();
        input.items = items;
        mut_self_trait.items.extend(
            mut_self_methods.into_iter().map(TraitItem::Fn)
        );
        mut_self_trait.ident = format_ident!(
            "ඞDyn{}OwnRef", mut_self_trait.ident,
        );
        mut_self_trait.attrs.push(parse_quote!(
            #[doc(hidden)]
        ));
        mut_self_trait
    };
    let UncheckedMutSelfTrait @ _ = &mut_self_trait.ident;
    input.supertraits.push(parse_quote!(
        #UncheckedMutSelfTrait #fwd_generics
    ));
    input.to_tokens(&mut ret);
    mut_self_trait.to_tokens(&mut ret);
    ret.extend({
        let mut generics_with_self = input.generics.clone();
        let num_lifetimes = input.generics.lifetimes().count();
        generics_with_self.params.insert(num_lifetimes, parse_quote_spanned!(Span::mixed_site()=>
            ඞSelf : ?::core::marker::Sized + #Trait #fwd_generics
        ));
        let mut generics_with_self_sized = generics_with_self.clone();
        generics_with_self_sized.make_where_clause().predicates.push(
            parse_quote_spanned!(Span::mixed_site()=>
                ඞSelf : Sized
            )
        );
        let (intro_generics_and_self, _, where_clause_unsized) = generics_with_self.split_for_impl();
        let (_, _, where_clause_sized) = generics_with_self_sized.split_for_impl();
        let own_ref_forwarding_impls =
            input
                .items
                .iter()
                .filter_map(|trait_item| own_ref_forwarding_impl(
                    trait_item,
                    Trait,
                    fwd_generics,
                    extension_trait_method_renaming_logic,
                ))
                .collect::<Vec<_>>()
        ;
        let own_ref_defs = own_ref_forwarding_impls.iter().cloned().map(|mut method| {
            method.default = None;
            method.semi_token = Some(
                Token![;](method.sig.paren_token.span.close())
            );
            method
        });
        quote_spanned!(Span::mixed_site()=>
            impl #intro_generics_and_self
                #UncheckedMutSelfTrait #fwd_generics
            for
                ඞSelf
            #where_clause_sized
            {
                #( #mut_self_method_impls )*
            }

            #extension_trait_pub
            trait #ExtensionTraitName #intro_generics
            #where_clause
            {
                #(#own_ref_defs)*
            }

            impl #intro_generics_and_self
                #ExtensionTraitName #fwd_generics
            for
                ::own_ref::OwnRef<'_, ඞSelf>
            #where_clause_unsized
            {
                #(#own_ref_forwarding_impls)*
            }
        )
    });
    Ok(ret)
}

fn is_owned_self_receiver(receiver: &Receiver)
  -> bool
{
    // self                      // : Self
    receiver.reference.is_none() && matches!(
        &*receiver.ty,
        Type::Path(TypePath {
            qself: None,
            path,
        }) if path.is_ident("Self")
    )
}

/// For each trait assoc item (_e.g._, assoc `fn`, or assoc type),
/// write what it would be when in the context of:
/// ```rust ,ignore
/// impl<ඞSelf : #Trait #fwd_impls, ...>
///     Trait #fwd_impls
/// for
///     OwnRef<'_, ඞSelf>
/// ```
fn own_ref_forwarding_impl(
    item: &TraitItem,
    Trait @ _: &Ident,
    fwd_generics: &TypeGenerics<'_>,
    extension_trait_method_renaming_logic: &args::RenamePattern,
) -> Option<TraitItemFn>
{
    let TraitItem::Fn(fun) = item
    else {
        return None;
    };
    if  matches!(
            fun.sig.receiver(),
            Some(self_) if is_owned_self_receiver(self_)
        )
        .not()
    {
        return None;
    }
    let mut ret = fun.clone();
    let self_ = fun.sig.receiver().map(|r| Ident::new("self", r.self_token.span())).unwrap();
    let mut each_fn_arg = Vec::<Ident>::new();
    ret.sig.inputs.iter_mut().zip(0..).skip(1).for_each(|(fn_arg, i)| {
        let FnArg::Typed(fn_arg) = fn_arg
        else {
            unreachable!();
        };
        let arg_ident = format_ident!("ඞ{i}", span=fn_arg.pat.span());
        *fn_arg.pat = Pat::Verbatim(quote!( #arg_ident ));
        each_fn_arg.push(arg_ident)
    });
    let forwarding_call = {
        let dyn_method_ownref = format_ident!(
            "ඞdyn_{}_ownref", fun.sig.ident,
        );
        let DynTraitOwnRef @ _ = format_ident!(
            "ඞDyn{Trait}OwnRef",
        );
        quote_spanned!(Span::mixed_site()=>
            unsafe {
                <ඞSelf as #DynTraitOwnRef #fwd_generics>::#dyn_method_ownref(
                    &mut **::core::mem::ManuallyDrop::<::own_ref::OwnRef<'_, ඞSelf>>::new(
                        #self_
                    )
                    #(, #each_fn_arg)*
                )
            }
        )
    };
    ret.sig.ident = extension_trait_method_renaming_logic.rename(&ret.sig.ident);
    ret.semi_token = None;
    ret.default = Some(parse_quote_spanned!(Span::mixed_site()=>
        {
            #forwarding_call
        }
    ));
    Some(ret)
}
